### ISSUE TITLE
Don't get template for remote commands

### ISSUE THREAD

**Issue by blb4github** [schwarzenbergf/irtrans#178]
## HA versions: 
Core 2025.1.4
Supervisor 2024.12.3
Operating System 14.1
Frontend 20250109.2

## Version of the custom_component
1.12

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
I don't see the template for the commands. When I use the development tools I do see:

<img width="1319" alt="Image" src="https://github.com/user-attachments/assets/c6e727a5-86cc-4d12-80f2-7fb5770d5e61" />

this automation is now working (setup in yaml):
```
alias: irtrans albrecht vol+
description: Fire IR command for vol+ of Remote albrecht
triggers: []
conditions: []
actions:
  - data:
      remote: albrecht
      ir_cmd: vol+
    target:
      entity_id: sensor.irtrans_sensor
    action: irtrans.send_irtrans_ir_command_albrecht
mode: single
```

## Debug log

[home-assistant_irtrans_2025-01-24T22-55-41.329Z.log](https://github.com/user-attachments/files/18543318/home-assistant_irtrans_2025-01-24T22-55-41.329Z.log)
